name: UI Automation Tests

on:
  push:
    branches:
      - master  # Or 'main', depending on your default branch

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'  # Change based on your project

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install

      - name: Run UI Tests
        run: mvn test

      - name: Install Node.js and Allure commandline
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
          sudo apt-get install -y nodejs
          sudo npm install -g allure-commandline --save-dev

      - name: Generate Allure Report (static HTML)
        run: |
          allure generate test-outputs/allure-results --clean -o  test-outputs/allure-report

      - name: Upload Allure report as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: test-outputs/allure-report
